movies/urls.py
from django.urls import path
from . import views

app_name = 'movies' 

urlpatterns = [
    path('', views.index , name='index'),
    path('<int:movie_id>', views.detail, name='detail')
]

vidly/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from api.models import MovieResource
from . import views
movie_resource = MovieResource()


urlpatterns = [
    path('', views.home, name= 'home'),
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('api/', include(movie_resource.urls))
] + static(settings.STATIC_URL, document_root =settings.STATIC_ROOT)

api/models.py
from django.db import models
from tastypie.resources import ModelResource
from movies.models import Movie

class MovieResource(ModelResource):
    class Meta:
        queryset = Movie.objects.all()
        resource_name = 'movies'
        excludes = ['date_created']
    

movies/models.py
from django.db import models
from django.utils import timezone
# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=255)
    
    def __str__(self):
        return self.name
    
class Movie(models.Model):
    title = models.CharField(max_length=255)
    release_year = models.IntegerField()
    number_in_stock = models.IntegerField()
    daily_rate = models.FloatField()
    genre = models.ForeignKey(Genre, on_delete= models.CASCADE)
    date_created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

api/views.py
from django.shortcuts import render

# Create your views here.

movies/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from .models import Movie
import redis

# Create your views here.

def connect():
    my_host_name = 'testpravredis.redis.cache.windows.net'
    my_password = 'Nfr7QWkbOM0U3ied7IXzQTxOYy60oTsTI9ZmcmHIcjk='
    r = redis.StrictRedis(host = my_host_name,
                          port = 6380,
                          password = my_password,
                          ssl = True)
    return r

def get_object_from_db(movie_id):
    
    db_object = get_object_or_404(Movie, pk=movie_id)
    return db_object

def index(request):
    
    movies = Movie.objects.all()
    return render(request, 'movies/index.html', {'movies':movies})

def detail(request, movie_id):
    redis_conn = connect()
    movie = redis_conn.get('movie'+str(movie_id))
    if  movie is None:
        redis_conn.set('movie'+ str(movie_id),str(get_object_from_db(movie_id)))
        movie = get_object_from_db(movie_id)
        return render(request, 'movies/details.html', {'movie':movie})
    else:
        movie = redis_conn.get('movie'+str(movie_id))
        movie = movie.decode('utf-8')
        return render(request, 'movies/details.html', {'movie': movie})

vidly/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home.html')

movies/templates/movies/details.html
{% extends 'base.html' %}

{% block content %}
<div class="container"  style="padding-top: 20px;">
    <div class="col s12 m2">
        <table class="highlight z-depth-4">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Genre</th>
                    <th>Stock</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ movie.title }}</td>
                    <td>{{ movie.genre }}</td>
                    <td>{{ movie.number_in_stock }}</td>
                </tr>
            </tbody>
        </table>
  </div>
</div>

{% endblock %}
    

movies/templates/movies/index.html
{% extends 'base.html' %}

{% block content%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <div class="container">
        <table class="highlight">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Genre</th>
                    <th>Stock</th>
                    <th>Daily rate</th>
                </tr>
            </thead>
            <tbody>
                {% for movie in movies %}
                <tr>                    
                    <td>
                        <a href="{% url 'movies:detail' movie.id  %}">{{ movie.title }}</a></td>
                    <td>{{ movie.genre }}</td>
                    <td>{{ movie.number_in_stock }}</td>
                    <td>{{ movie.daily_rate }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <p>path</p>
</body>

</html>
{% endblock %}

vidly/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<title>
  Vidly
</title>
<head>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="{% static 'materialize/css/materialize.min.css' %}"
        media="screen,projection" />

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>

<body>
    <nav>
        <div class="nav-wrapper blue lighten-3">
          <a href="{% url 'home' %}" class="brand-logo" style="margin-left: 10px;">Vidly</a>
          </ul>
        </div>
      </nav>
    {% block content %}

    {% endblock %}
    <!--JavaScript at end of body for optimized loading-->
    <script type="text/javascript" src="{% static 'materialize/js/materialize.min.js' %}"></script>
</body>

</html>

vidly/templates/home.html
{% extends 'base.html' %}


{% block content %}
<div class="contaner center" style="margin-top: 20px;">
    <a href = "{% url 'movies:index' %}" onclick="M.toast({html: 'Loading movies list !'})" class="btn waves-effect default" style="background-color:slategray;"></onclick=>Movies</a>

</div>

{% endblock %}
    